### ISSUE TITLE
isnt downloading

### ISSUE THREAD

**Issue by devlin016** [cabernetwork/provider_video_m3u#3]
Plugin doesnt seem to work for me. I tried a https link and a local linux file. everything else on cabernet seems to work.

```
2023-12-08 10:35:12,141-DEBUG:schedule Running job Job(interval=1, unit=days, do=exec_trigger, args=({'uuid': 'B39EEB94-95DE-11EE-AB3F-B827EBC5476E', 'area': 'Channels', 'title': 'Refresh Audio Channels', 'timetype': 'daily', 'timelimit': -1, 'timeofday': '04:35', 'dayofweek': None, 'interval': -1, 'randdur': -1, 'taskid': 'B39E209C-95DE-11EE-AB3F-B827EBC5476E', 'namespace': 'M3U', 'instance': 'default', 'funccall': 'refresh_channels', 'lastran': None, 'duration': None, 'priority': 20, 'threadtype': 'inline', 'active': 0, 'description': 'Pulls channel lineup from M3U'},), kwargs={})
2023-12-08 10:35:12,146-NOTICE:scheduler Running inline task Channels:Refresh Audio Channels
2023-12-08 10:35:12,168-WARNING:decorators get uri called from <function TMPMgmt.download_file at 0x74f1e268> with retires=m3u
2023-12-08 10:35:12,169-ERROR:scheduler UNEXPECTED EXCEPTION on GET='>' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "/tmp/cabernet/lib/schedule/scheduler.py", line 161, in call_trigger
    results = call_f()
  File "/tmp/cabernet/lib/plugins/plugin_instance_obj.py", line 152, in refresh_channels
    return self.channels.refresh_channels()
  File "/tmp/cabernet/lib/plugins/plugin_channels.py", line 134, in refresh_channels
    ch_dict = self.get_channels()
  File "/tmp/cabernet/plugins_ext/provider_video_m3u/lib/channels.py", line 68, in get_channels
    dn_filename = self.tmp_mgmt.download_file(url, TMP_FOLDERNAME, None, file_type)
  File "/tmp/cabernet/lib/common/decorators.py", line 62, in wrapper_func
    while i > is_done:
TypeError: '>' not supported between instances of 'str' and 'int'
2023-12-08 10:35:12,188-DEBUG:web_handler [192.168.47.7] "GET /api/schedulehtml?task=B39E209C-95DE-11EE-AB3F-B827EBC5476E&run=1 HTTP/1.1" 200 -
2023-12-08 10:35:12,222-DEBUG:web_handler [192.168.47.7] "GET /modules/scheduler/scheduler.js HTTP/1.1" 200 -
2023-12-08 10:35:12,224-DEBUG:web_handler [192.168.47.7] "GET /modules/scheduler/scheduler.css HTTP/1.1" 200 -
2023-12-08 10:35:13,248-DEBUG:schedule Running job Job(interval=1, unit=days, do=exec_trigger, args=({'uuid': 'B39EEB94-95DE-11EE-AB3F-B827EBC5476E', 'area': 'Channels', 'title': 'Refresh Audio Channels', 'timetype': 'daily', 'timelimit': -1, 'timeofday': '04:35', 'dayofweek': None, 'interval': -1, 'randdur': -1, 'taskid': 'B39E209C-95DE-11EE-AB3F-B827EBC5476E', 'namespace': 'M3U', 'instance': 'default', 'funccall': 'refresh_channels', 'lastran': None, 'duration': None, 'priority': 20, 'threadtype': 'inline', 'active': 0, 'description': 'Pulls channel lineup from M3U'},), kwargs={})
2023-12-08 10:35:13,252-NOTICE:scheduler Running inline task Channels:Refresh Audio Channels
2023-12-08 10:35:13,259-WARNING:decorators get uri called from <function TMPMgmt.download_file at 0x74f1e268> with retires=m3u
2023-12-08 10:35:13,260-ERROR:scheduler UNEXPECTED EXCEPTION on GET='>' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "/tmp/cabernet/lib/schedule/scheduler.py", line 161, in call_trigger
    results = call_f()
  File "/tmp/cabernet/lib/plugins/plugin_instance_obj.py", line 152, in refresh_channels
    return self.channels.refresh_channels()
  File "/tmp/cabernet/lib/plugins/plugin_channels.py", line 134, in refresh_channels
    ch_dict = self.get_channels()
  File "/tmp/cabernet/plugins_ext/provider_video_m3u/lib/channels.py", line 68, in get_channels
    dn_filename = self.tmp_mgmt.download_file(url, TMP_FOLDERNAME, None, file_type)
  File "/tmp/cabernet/lib/common/decorators.py", line 62, in wrapper_func
    while i > is_done:
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by rocky4546** [comment]
what version of cabernet and m3u plugin are you running?  If you are running 0.1.12 on m3u, try to upgrade to 0.1.13

**Comment by devlin016** [comment]
> what version of cabernet and m3u plugin are you running? If you are running 0.1.12 on m3u, try to upgrade to 0.1.13

after updating plugin seems to fix issue thank you sir.
